### ISSUE TITLE
Fix Login (for tests and in general)

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#114]
Tests run locally fail because they cannot succeed the login procedure.

## todo
- [x] fix login procedure when using `webtest.TestApp`
- [x] enable for travis (ref #140, commit 172bd0d)

## error detail

```
. . . 
Starting Magpie app...
.......E....ssssssssssss
======================================================================
ERROR: setUpClass (tests.test_magpie_api.TestMagpieAPI_AdminAuth_Local)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/francis/VISI/PAVICS/magpie/tests/test_magpie_api.py", line 80, in setUpClass
    cls.check_requirements()
  File "/home/francis/VISI/PAVICS/magpie/tests/interfaces.py", line 113, in check_requirements
    assert cls.headers and cls.cookies, cls.require
AssertionError: cannot run tests without logged in 'administrators' user

======================================================================
ERROR: setUpClass (tests.test_magpie_ui.TestMagpieUI_AdminAuth_Local)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/francis/VISI/PAVICS/magpie/tests/test_magpie_ui.py", line 67, in setUpClass
    cls.headers, cls.cookies = utils.check_or_try_login_user(cls.url, cls.usr, cls.pwd, use_ui_form_submit=True)
  File "/home/francis/VISI/PAVICS/magpie/tests/utils.py", line 142, in check_or_try_login_user
    resp = app_or_url.get(url='/ui/login')
  File "/home/francis/.conda/envs/magpie/lib/python2.7/site-packages/webtest/app.py", line 331, in get
    expect_errors=expect_errors)
  File "/home/francis/.conda/envs/magpie/lib/python2.7/site-packages/webtest/app.py", line 651, in do_request
    self._check_status(status, res)
  File "/home/francis/.conda/envs/magpie/lib/python2.7/site-packages/webtest/app.py", line 683, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/ui/login)
{"code": 500, "route_name": "/ui/login", "detail": "Internal Server Error. Unhandled exception occurred.", "request_url": "http://localhost/ui/login", "type": "application/json", "method": "GET"}

======================================================================
ERROR: test_Login (tests.test_magpie_ui.TestMagpieUI_NoAuth_Local)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/francis/VISI/PAVICS/magpie/tests/interfaces.py", line 731, in test_Login
  File "/home/francis/VISI/PAVICS/magpie/tests/utils.py", line 369, in check_UpStatus
    resp = test_request(test_class.url, method, path, cookies=test_class.cookies)
  File "/home/francis/VISI/PAVICS/magpie/tests/utils.py", line 90, in test_request
    return app_or_url.get(path, **kwargs)
  File "/home/francis/.conda/envs/magpie/lib/python2.7/site-packages/webtest/app.py", line 331, in get
    expect_errors=expect_errors)
  File "/home/francis/.conda/envs/magpie/lib/python2.7/site-packages/webtest/app.py", line 651, in do_request
    self._check_status(status, res)
  File "/home/francis/.conda/envs/magpie/lib/python2.7/site-packages/webtest/app.py", line 683, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/ui/login)
{"code": 500, "route_name": "/ui/login", "detail": "Internal Server Error. Unhandled exception occurred.", "request_url": "http://localhost/ui/login", "type": "application/json", "method": "GET"}

----------------------------------------------------------------------
Ran 75 tests in 2291.536s

FAILED (errors=3, skipped=60)
```

**Comment by fmigneault** [comment]
Tests work using `MAGPIE_TEST_REMOTE_SERVER_URL=http://localhost:2001/magpie` using another instance running Magpie on said port.
"Local" tests using `webtest.TestApp` still fail (cannot find route `/signin_interal`) 
see #ergo/ziggurat_foundations#61
