### ISSUE TITLE
[BUG] Unable to edit user email with Magpie 3.14.0

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#459]
**Describe the bug**

Is user update disabled unless `MAGPIE_USER_REGISTRATION_ENABLED` is activated?  That feels wrong to me.

Went here https://pavics.ouranos.ca/magpie/ui/users/logan/default to edit user mail, got the follow error in server log:

```
[2021-08-05 16:51:34,118] INFO       [ThreadPoolExecutor-0_3][magpie.api.requests] User 'admin' is authenticated
[2021-08-05 16:51:34,119] WARNING    [ThreadPoolExecutor-0_3][magpie.utils] Constant could not be found: MAGPIE_USER_REGISTRATION_ENABLED (using default: False)
[2021-08-05 16:51:34,127] INFO       [ThreadPoolExecutor-0_3][magpie.utils] Request: [GET pavics.ouranos.ca:443 /magpie/users/logan/groups]
[2021-08-05 16:51:34,156] INFO       [ThreadPoolExecutor-0_3][magpie.utils] Request: [GET pavics.ouranos.ca:443 /magpie/groups]
[2021-08-05 16:51:34,173] INFO       [ThreadPoolExecutor-0_3][magpie.utils] Request: [GET pavics.ouranos.ca:443 /magpie/services]
[2021-08-05 16:51:34,214] INFO       [ThreadPoolExecutor-0_3][magpie.utils] Request: [GET pavics.ouranos.ca:443 /magpie/users/logan]
[2021-08-05 16:51:34,242] INFO       [ThreadPoolExecutor-0_3][magpie.utils] Request: [PATCH pavics.ouranos.ca:443 /magpie/users/logan]
[2021-08-05 16:51:34,262] ERROR      [ThreadPoolExecutor-0_3][magpie.utils] Constant could not be found: MAGPIE_USER_REGISTRATION_ENABLED
[2021-08-05 16:51:34,262] ERROR      [ThreadPoolExecutor-0_3][magpie.api.generic] Request exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 683, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/config/views.py", line 169, in __call__
    return view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/opt/local/src/magpie/magpie/api/management/user/user_views.py", line 78, in update_user_view
    uu.update_user(user, request, new_user_name, new_password, new_email, new_status)
  File "/opt/local/src/magpie/magpie/api/management/user/user_utils.py", line 197, in update_user
    if update_email and asbool(get_constant("MAGPIE_USER_REGISTRATION_ENABLED", request)):
  File "/opt/local/src/magpie/magpie/constants.py", line 273, in get_constant
    level=logging.ERROR, exception=LookupError)
  File "/opt/local/src/magpie/magpie/utils.py", line 168, in raise_log
    raise exception(msg)
LookupError: Constant could not be found: MAGPIE_USER_REGISTRATION_ENABLED
[2021-08-05 16:51:34,263] ERROR      [ThreadPoolExecutor-0_3][magpie.ui.utils] Unexpected API error under UI operation. [{'path': '/users/logan', 'url': 'https://pavics.ouranos.ca/magpie/users/logan', 'detail': 'Internal Server Error. Unhandled exception occurred.', 'method': 'PATCH', 'exception': 'LookupError', 'code': 500, 'type': 'application/json'}]
Traceback (most recent call last):
  File "/opt/local/src/magpie/magpie/ui/utils.py", line 147, in wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/opt/local/src/magpie/magpie/ui/management/views.py", line 228, in edit_user
    check_response(resp)
  File "/opt/local/src/magpie/magpie/ui/utils.py", line 45, in check_response
    raise exception_response(response.status_code, body=response.text)
pyramid.httpexceptions.HTTPInternalServerError: The server has either erred or is incapable of performing the requested operation.
[2021-08-05 16:51:34,271] INFO       [ThreadPoolExecutor-0_3][magpie.utils] Request: [POST pavics.ouranos.ca:443 /magpie/ui/error]
[2021-08-05 16:51:34,272] INFO       [ThreadPoolExecutor-0_3][magpie.api.requests] User 'admin' is authenticated

```

**To Reproduce**
From PAVICS stack version https://github.com/bird-house/birdhouse-deploy/tree/1.14.0

**Comment by fmigneault** [comment]
Update should be allowed by any admin or the user itself when `MAGPIE_USER_REGISTRATION_ENABLED=false`. 
Otherwise, only admin can update when `MAGPIE_USER_REGISTRATION_ENABLED=true`. 
I think the error here is specific to `MAGPIE_USER_REGISTRATION_ENABLED` not found (`LookupError`). 
This should be adjusted to allow default `false` when setting is omitted.
